# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    private_key: 'file://%kernel.project_dir%/var/private.key'
    encryption_key: '%kernel.project_dir%/var/encryption.key'
    access_token_ttl: PT1H
    refresh_token_ttl: P1M
    auth_code_ttl: PT1M
    enable_client_credentials_grant: true
    enable_password_grant: false
    enable_refresh_token_grant: true
    enable_auth_code_grant: true
    enable_implicit_grant: false

    ad_enabled: false
    ad_domain_controllers: [ 'ACME-DC01.corp.acme.org' ]
    ad_base_dn: 'dc=corp,dc=acme,dc=org'
    ad_port: 389
    ad_admin_username: 'admin@corp.acme.org'
    ad_admin_password: 'password'
    ad_query_fetch_users: '(&(objectCategory=person)(objectClass=user))'
    ad_login_attribute: 'sAMAccountName'
    ad_use_ssl: false

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\OAuth\UserRepositoryFactory:
        calls:
            - setIsActiveDirectoryEnabled: ['%ad_enabled%']

    League\OAuth2\Server\Repositories\UserRepositoryInterface:
        factory: ['@App\OAuth\UserRepositoryFactory', 'create']

    App\OAuth\AuthorizationServerFactory:
        calls:
            - setPrivateKey: ['%private_key%']
            - setEncryptionKey: ['%encryption_key%']
            - setAccessTokenTtl: ['%access_token_ttl%']
            - setRefreshTokenTtl: ['%refresh_token_ttl%']
            - setAuthCodeTtl: ['%auth_code_ttl%']
            - enableClientCredentialsGrant: ['%enable_client_credentials_grant%']
            - enablePasswordGrant: ['%enable_password_grant%']
            - enableRefreshTokenGrant: ['%enable_refresh_token_grant%']
            - enableAuthCodeGrant: ['%enable_auth_code_grant%']
            - enableImplicitGrant: ['%enable_implicit_grant%']

    League\OAuth2\Server\AuthorizationServer:
        factory: ['@App\OAuth\AuthorizationServerFactory', 'create']

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        class: Nyholm\Psr7\Factory\Psr17Factory

    League\Event\Emitter:
        class: League\Event\Emitter
        calls:
            - useListenerProvider: ['@App\Service\SymfonyLeagueEventListenerProvider']

    App\Tests\Fixtures\:
        resource: '%kernel.project_dir%/tests/Fixtures/'